ControleDeContas/Models/Conta.cs
namespace ControleDeContas.Models
{
    public class Conta
    {
        public int Id { get; set; }
        public string? Nome { get; set; }
        public string? Detalhes { get; set; }


    }
}

ControleDeContas/Models/ErrorViewModel.cs
namespace ControleDeContas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleDeContas/Models/Movimentacao.cs
namespace ControleDeContas.Models
{
    public class Movimentacao
    {
        public long Id { get; set; }
        public DateTime DataVencimento { get; set; }
        public DateTime DataPagamento{ get; set; }

        public decimal ValorDevido { get; set; }
        public decimal ValorPago { get; set; }

        public int TotalParcelas { get; set; }
        public int NumeroParcelas { get; set; }

    }
}

ControleDeContas/Controllers/ContaController.cs
using ControleDeContas.Models;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContas.Controllers
{
    public class ContaController : Controller
    {
        private static IList<Conta> contas = new List<Conta>()
        {
            new Conta()
            {
                Id= 1,
                Nome = "Pedro",
                Detalhes = "Conta poupança",
            },
        };
        public IActionResult Index()
        {
            return View(contas);
        }
   

public IActionResult Create()
{
    return View();
}

[HttpPost]
[ValidateAntiForgeryToken]
public IActionResult Create(Conta conta)
{
    conta.Id = contas.Select(i => i.Id).Max() + 1;
    contas.Add(conta);
    return RedirectToAction("Index");
}

public IActionResult Edit(long id)
{
    return View(contas.Where(i => i.Id == id).First());
}

[HttpPost]
[ValidateAntiForgeryToken]
public IActionResult Edit(Conta conta)
{
    contas.Remove(contas.Where(i => i.Id == conta.Id).First());
    contas.Add(conta);
    return RedirectToAction("Index");
}
public IActionResult Details(long id)
{
    return View(contas.Where(i => i.Id == id).First());
}
public IActionResult Delete(long id)
{
    return View(contas.Where(i => i.Id == id).First());
}
[HttpPost]
[ValidateAntiForgeryToken]
public IActionResult Delete(Movimentacao conta)
{
    contas.Remove(contas.Where((i) => i.Id == conta.Id).First());
    return RedirectToAction("Index");
}



    }
}

ControleDeContas/Controllers/HomeController.cs
using ControleDeContas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ControleDeContas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControleDeContas/Controllers/MovimentacaoController.cs
using ControleDeContas.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Cryptography;

namespace ControleDeContas.Controllers
{
    public class MovimentacaoController : Controller
    {
        private static List<Movimentacao> movimentacoes = new List<Movimentacao>()
        {
            new Movimentacao()
            {
                Id= 1,
                DataVencimento = DateTime.Today,
                DataPagamento = DateTime.Today,
                ValorDevido = 5000,
                ValorPago = 5000,
                TotalParcelas= 10,
                NumeroParcelas= 5,

            }
            
        };
        public IActionResult Index()
        {
            return View(movimentacoes);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Movimentacao movimentacao)
        {
            movimentacao.Id = movimentacoes.Select(i => i.Id).Max() + 1;
            movimentacoes.Add(movimentacao);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(long id)
        {
            return View(movimentacoes.Where(i => i.Id == id).First());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Movimentacao movimentacao)
        {
            movimentacoes.Remove(movimentacoes.Where(i => i.Id == movimentacao.Id).First());
            movimentacoes.Add(movimentacao);
            return RedirectToAction("Index");
        }
        public IActionResult Details(long id)
        {
            return View(movimentacoes.Where(i => i.Id == id).First());
        }
        public IActionResult Delete(long id)
        {
            return View(movimentacoes.Where(i => i.Id == id).First());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Movimentacao movimentacao)
        {
            movimentacoes.Remove(movimentacoes.Where((i) => i.Id == movimentacao.Id).First());
            return RedirectToAction("Index");
        }



    }
}

ControleDeContas/Views/Conta/Create.cshtml
@model ControleDeContas.Models.Conta

@{
    ViewData["Title"] = "Adionando uma nova conta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<h4>Conta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detalhes" class="control-label"></label>
                <input asp-for="Detalhes" class="form-control" />
                <span asp-validation-for="Detalhes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista de Contas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControleDeContas/Views/Conta/Delete.cshtml
@model ControleDeContas.Models.Conta

@{
    ViewData["Title"] = "Excluir conta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<h3>Confirma a exclusão dessa conta?</h3>
<hr />
<div>
    <h4>Conta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Detalhes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Detalhes)
        </dd>
    </dl>
         <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para a lista das contas</a>
        </form>
</div>

ControleDeContas/Views/Conta/Details.cshtml
@model ControleDeContas.Models.Conta

@{
    ViewData["Title"] = "Detalhes da conta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div>
    <h4>Conta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Detalhes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Detalhes)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    <a asp-action="Index">Voltar para a listas das contas</a>
</div>

ControleDeContas/Views/Conta/Edit.cshtml
@model ControleDeContas.Models.Conta

@{
    ViewData["Title"] = "Editar conta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Conta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detalhes" class="control-label"></label>
                <input asp-for="Detalhes" class="form-control" />
                <span asp-validation-for="Detalhes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista de Contas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControleDeContas/Views/Conta/Index.cshtml
@model IEnumerable<ControleDeContas.Models.Conta>

@{
    ViewData["Title"] = "Lista de Contas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Adicionar uma nova conta</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Detalhes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Detalhes)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

ControleDeContas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Seja bem vindo!</h1>
    <h2>Contas e Movimentações</h2>
    <p>Projeto desenvolvido na unidade de PROGRAMAÇÃO ORIENTADA A OBJETOS II</p>
    <h3>Professor:ROSENCLEVER LOPES GAZONI</h3>
    <p>Para mais informações ,ou o código do projeto acesse -> <a href="https://github.com/MMVSILVA" target="_blank">Meu Github</a>.</p>
</div>

ControleDeContas/Views/Movimentacao/Create.cshtml
@model ControleDeContas.Models.Movimentacao

@{
    ViewData["Title"] = "Adionando uma nova movimentação";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<h4>Movimentações</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="DataVencimento" class="control-label"></label>
                <input asp-for="DataVencimento" class="form-control" />
                <span asp-validation-for="DataVencimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataPagamento" class="control-label"></label>
                <input asp-for="DataPagamento" class="form-control" />
                <span asp-validation-for="DataPagamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorDevido" class="control-label"></label>
                <input asp-for="ValorDevido" class="form-control" />
                <span asp-validation-for="ValorDevido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorPago " class="control-label"></label>
                <input asp-for="ValorPago " class="form-control" />
                <span asp-validation-for="ValorPago " class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalParcelas" class="control-label"></label>
                <input asp-for="TotalParcelas" class="form-control" />
                <span asp-validation-for="TotalParcelas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroParcelas" class="control-label"></label>
                <input asp-for="NumeroParcelas" class="form-control" />
                <span asp-validation-for="NumeroParcelas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista de movimentações</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControleDeContas/Views/Movimentacao/Details.cshtml
@model ControleDeContas.Models.Movimentacao

@{
    ViewData["Title"] = "Detalhes da Movimentação";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewData["Title"]</h1>

<hr />
<div>
    <h4>Movimentação Diárias</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataVencimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataVencimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataPagamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataPagamento)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorDevido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorDevido)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorPago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorPago)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalParcelas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalParcelas)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroParcelas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroParcelas)
        </dd>

    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    <a asp-action="Index">Voltar para a listas de movimentações</a>
</div>

ControleDeContas/Views/Movimentacao/Edit.cshtml
@model ControleDeContas.Models.Movimentacao

@{
    ViewData["Title"] = "Editar Movimentação";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Movimentação</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="DataVencimento" class="control-label"></label>
                <input asp-for="DataVencimento" class="form-control" />
                <span asp-validation-for="DataVencimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataPagamento" class="control-label"></label>
                <input asp-for="DataPagamento" class="form-control" />
                <span asp-validation-for="DataPagamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorDevido" class="control-label"></label>
                <input asp-for="ValorDevido" class="form-control" />
                <span asp-validation-for="ValorDevido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorPago " class="control-label"></label>
                <input asp-for="ValorPago " class="form-control" />
                <span asp-validation-for="ValorPago " class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalParcelas" class="control-label"></label>
                <input asp-for="TotalParcelas" class="form-control" />
                <span asp-validation-for="TotalParcelas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroParcelas" class="control-label"></label>
                <input asp-for="NumeroParcelas" class="form-control" />
                <span asp-validation-for="NumeroParcelas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista de movimentações</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ControleDeContas/Views/Movimentacao/Index.cshtml
@model IEnumerable<ControleDeContas.Models.Movimentacao>

@{
    ViewData["Title"] = "Movimentações";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Adicionar uma nova conta</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataVencimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataPagamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorDevido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorPago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalParcelas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroParcelas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataVencimento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataPagamento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorDevido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorPago)
                 </td>
                 <td>
                    @Html.DisplayFor(modelItem => item.TotalParcelas)
                 </td>
                 <td>
                    @Html.DisplayFor(modelItem => item.NumeroParcelas)
                 </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

ControleDeContas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ControleDeContas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControleDeContas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ControleDeContas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="Index">Conta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movimentacao" asp-action="Index">Movimentação</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ControleDeContas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>